### ISSUE TITLE
Youtube component disappearing immediately after page loads

### ISSUE THREAD

**Issue by lofti198** [tjallingt/react-youtube#355]
Youtube component is very cool, but disappearing immediately after page loads. Tested with example from here https://github.com/tjallingt/react-youtube . What can be the reason?

**Comment by avganka** [comment]
II had the same issue. The reason is the changed rendering of react 18. Need to wait for an update or use the old method

`import ReactDOM from 'react-dom';

ReactDOM.render(
  <React.StrictMode>
    <App/>
  </React.StrictMode>,
  document.getElementById('root'));`

instead of 
`import ReactDOM from 'react-dom/client';

const root = ReactDOM.createRoot(document.getElementById('root') as HTMLElement);
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);`

**Comment by lofti198** [comment]
Thank you! It works just fine!

**Comment by ruisaraiva19** [comment]
@lofti198 @avganka can you give version [9.0.2](https://github.com/tjallingt/react-youtube/releases/tag/v9.0.2) a try? It should work with React 18 new strict mode.

**Comment by avganka** [comment]
@ruisaraiva19 yeah, thank you! Checked. Works great

**Comment by jaredhill4** [comment]
Hey @ruisaraiva19, I see that you said it is fixed, but from what I can tell, the video is still being destroyed immediately onload and you are just reloading it. Do you have a fix where the video isn't loaded twice?
