### ISSUE TITLE
Package has a double on npm

### ISSUE THREAD

**Issue by Fr33maan** [tjallingt/react-youtube#73]
According to [npm doc](https://www.npmjs.com/package/lapanoid-react-youtube) I should pass an url but it does not work as I must pass a `videoId`.

Sounds stupid but I lost 20 minutes

**Comment by goto-bus-stop** [comment]
That link goes the npm page for a package called `lapanoid-react-youtube`…which seems to be an exact copy of an older version of this module. (?)

This module is published to npm at https://npmjs.com/package/react-youtube, and the docs are up to date there :)

**Comment by prisonier** [comment]
The strangest thing is that the github repo link comes here ...

**Comment by tjallingt** [comment]
Not sure what happened there...
It seems like a bit of bad manners to upload someone else's module to NPM :confused: 
perhaps this is the same person: @lapanoid ?
If so would you be willing to remove your package from NPM (or at least removing this repository from the `repository` field in package.json so people do not confuse the packages)

**Comment by l1br3** [comment]
I don't think unpublish it is the right solution as people whom relies on it will experience some troubles.

Plus I think it is not possible to unpublish a package older than 24 hours, there have been a big issue about this a time ago. 

[See here for npm unpublish policy](http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy)

**Comment by tjallingt** [comment]
There are no dependents (npm packages that depend on his package) so he is free to remove it by contacting NPM support.

As far as I can tell it is a direct copy of our package, if it isn't and there is a reason for it to stay on NPM (say people are using it as a modified version of our package) then he should (at the very least) not link it to this repository.

As it is right now I would dare say it is dangerous for that package to stay up on NPM because people will think they are installing the code from this repository but actually they could be installing anything (which is what caused this whole thing about un-publishing in the first place).
